<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Hello {nicename}, ' => 'Hallo {nicename}, ',
  'Account Login' => 'Konto Anmeldung',
  'Account Signup' => 'Konto Registrierung',
  'Accounts' => 'Konten',
  'Are you sure you want to delete your account?' => 'Sind Sie sicher, dass Sie Ihr Konto löschen möchten?',
  'Auth Key' => 'Bestätigungsschlüssel',
  'Created At' => 'Erstellt am',
  'Delete' => 'Löschen',
  'Email' => 'E-Mail-Adresse',
  'Follow the link below to reset your password:' => 'Folgen Sie dem unten stehenden Link, um Ihr Passwort zurückzusetzen:',
  'Forgot your password?' => 'Passwort vergessen?',
  'ID' => 'ID',
  'Incorrect username or password. Please try again.' => 'Benutzername oder Passwort ist falsch. Bitte versuchen Sie es noch einmal.',
  'Login' => 'Anmelden',
  'New password has been saved. You can use it to login now.' => 'Das neue Passwort wurde gespeichert. Sie können es nun verwenden, um sich anzumelden.',
  'Password' => 'Passwort',
  'Password Hash' => 'Passwort Prüfsumme',
  'Password Reset Token' => 'Passwort Wiederherstellungsschlüssel',
  'Password reset for {appname}' => 'Passwort Wiederherstellung für {appname}',
  'Password reset token cannot be blank.' => 'Der Passwort Wiederherstellungsschlüssel darf nicht leer sein.',
  'Please check your email for further instructions.' => 'Bitte überprüfen Sie Ihr E-Mail Postfach für weitere Anweisungen.',
  'Please choose your new password.' => 'Bitte wählen Sie Ihr neues Passwort.',
  'Please fill out the email for your account. A link to the password recovery will be sent there.' => 'Bitte geben Sie hier die E-Mail-Adresse Ihres Kontos an. Ein Link zur Passwort Wiederherstellung wird anschließend an diese Adresse gesendet.',
  'Please fill out the following fields to create a new account.' => 'Um ein neues Konto zu erstellen, füllen Sie bitte die folgenden Felder aus.',
  'Remember Me' => 'Angemeldet bleiben',
  'Reset your password' => 'Passwort zurücksetzen',
  'Role' => 'Berechtigung',
  'Save' => 'Speichern',
  'Send' => 'Absenden',
  'Signup' => 'Registrieren',
  'Sorry, we are unable to reset password for email provided.' => 'Es tut uns leid, wir sind nicht in der Lage das Passwort für dieses Konto zurückzusetzen. Bitte kontaktieren Sie unseren Support.',
  'Status' => 'Status',
  'The requested page does not exist.' => 'Die gewünschte Seite ist nicht vorhanden.',
  'There is no account with this email.' => 'Es gibt kein Konto mit dieser E-Mail-Adresse.',
  'This email is already registered. Do you already have an account?' => 'Diese E-Mail-Adresse ist bereits vergeben. Haben Sie bereits ein Konto?',
  'This username is already registered. Do you already have an account?' => 'Dieser Benutzername ist bereits vergeben. Haben Sie bereits ein Konto?',
  'Update' => 'Aktualisieren',
  'Updated At' => 'Aktualisiert am',
  'Username' => 'Benutzername',
  'Wrong or expired password reset token.' => 'Falscher oder abgelaufener Passwort Wiederherstellungsschlüssel.',
  '{nicename}´s Profile' => '{nicename}´s Profil',
);
